version: '3.8'
services:
  api:
    build: .
    container_name: alineador-api
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - REDIS_URL=${REDIS_URL}
    command: ["node", "dist/server.js"]

